#
# The root of the yaml tree.
#
system_under_test:
    system:
        submission_name:            str( min=1 )
        friendly_description:       str( min=1 )
        architecture:
            storage_location:       enum( 'remote', 'local', 'remote_and_local' )
            benchmark_API:          enum( 'file', 'object', 'block' )   # what the benchmark uses
            product_API:            enum( 'file', 'object', 'block' )   # What the product supports
            client_footprint:       enum( 'open_source', 'closed_source', 'none' )
            client_installation:    enum( 'in_box', 'installable', 'n/a' )
        capabilities:
            multi_host:             bool( )      # False is used for local storage
            simultaneous_write:     bool( )      # Are simultaneous writes by multiple hosts supported?
            simultaneous_read:      bool( )      # Are simultaneous reads by multiple hosts supported?
            remap_time_in_seconds:  int( min=0 )  # Time required to go from writing to reading
    storage:                        list( include( 'node_description' ), required=False )
    switches:                       list( include( 'switch_description' ), required=False )
    total_rack_units:               int( min=0 )  # Not including clients
    clients:                        list( include( 'node_description' ), required=True )

---
# 
# 
# 
node_description:
    friendly_description:       str( min=1 )
    quantity:                   int( min=1 )
    chassis:
        model_name:             str( min=1 )
        rack_units:             int( min=1 )
        cpu_model:              str( min=1 )
        cpu_qty:                int( min=1 )
        cpu_cores:              int( min=1 )
        memory_capacity:        int( min=1 )  # in GiB, eg: 256
        power:                  include( 'power_device' )
    networking:                 list( include( 'network_instance' ), required=False )
    drives:                     list( include( 'drive_instance' ), required=False )
    operating_system:
        name:                   str( min=1 )
        version:                str( min=1 )
    environment:                list( include( 'key_value' ), required=False ) # Just non-default values
    sysctl:                     list( include( 'key_value' ), required=False ) # Just non-default values

---
#
# All non-default tunings for OS need to be listed
#
key_value:
    name:                       str( min=1 )
    value:                      str( min=1 )

---
#
#
#
network_instance:
    type:                       enum( 'ethernet', 'infiniband', 'other' )
    speed:                      int( min=1 )  # in Gigabits/s
    traffic:                    list( enum( 'management', 'data', 'metadata', 'backend' ), min=1 )
    unit_count:                 int( min=1 )  # Number of ports that look like this

---
#
# Not including boot drives.
#
drive_instance:
    vendor_name:                str( min=1 )
    model_name:                 str( min=1 )
    interface:                  enum( 'nvme', 'SAS', 'SATA', 'other' )
    capacity_in_GB:             int( min=1 )  # in base 10 GB, not in GiB
    unit_count:                 int( min=1 )  # Number of drives that look like this

---
#
#
#
switch_description:
    vendor_name:                str( min=1 )
    model_name:                 str( min=1 )
    ports:                      list( include( 'network_instance' ), min=1 )
    configuration:              list( include( 'key_value' ), required=False ) # Just non-default values
    rack_units:                 int( min=1 )
    power:                      include( 'power_device' )
    unit_count:                 int( min=1 )  # Number of switches that look like this

---
#
#
#
power_device:
    min_psus_active:            int( min=1 )
    psus_configured:            list( include( 'power_supply' ), min=1 )

---
#
#
#
power_supply:
    Name:                       str( min=1 )
    PowerCapacityWatts:         int( min=1 )
    Efficiency:                 enum( 'Gold', 'Platinum', 'Titanium', 'Ruby' )



# Each on-prem MLPerf submission include the nameplate / design power of the submitted System Under Test (SUT).
# This information will complement existing measured-power methodologies and provide a uniform baseline reference across systems and vendors.
# The intent is not to replace measured power but to give additional visibility into the designed power capacity of submitted systems.
# By including design power, MLPerf can help stakeholders—submitters, reviewers, and end users—better contextualize energy efficiency results,
# improve reproducibility, and align with related MLCommons initiatives such as Storage and Training benchmarks that already collect rated
# power information.We propose to include the following:
# Option 1 (Preferred): Submit the aggregate nameplate / design power for the SUT, listing all major components (accelerators, CPUs, storage, networking, etc.).
# Option 2: Provide per-component TDP/TGP data and a summarized total for the SUT.
# === Reporting YAML FormatThe reported design power (total of all needed PSU capacities in watts) will appear alongside the measured-power and non-power views,
# clearly labeled as “Design Power.”This data is reported through a yaml file.
# The structure of the YAML file is a hierarchy of components, with the power capacity based on the DMTF RedFish PowerSupply schema.
# For example, a simple single-device system can have a single level:
# 
# My Device:
# - Description: 'Optional Description'
#   Min PSUs Needed: 1
#   PSUs:
#     - Name: PSU 1
#       PowerCapacityWatts: 1200
#     - Name: PSU 2
#       PowerCapacityWatts: 1200
#
# A more complex system can have two (or more) levels:
# My System:
# - My Rack 1:
#   - My Server 1:
#     - Description: 'Optional Description'
#       Min PSUs Needed: 1
#       PSUs:
#       - Name: PSU 1
#         PowerCapacityWatts: 1200
#       - Name: PSU 2
#         PowerCapacityWatts: 1200
#   - My Switch 1:
#     - Description: 'Optional Description'
#       Min PSUs needed: 1
#       PSUs:
#       - Name: PSU 1
#         PowerCapacityWatts: 1200
#       - Name: PSU 2
#         PowerCapacityWatts: 1200
# 
# The labels “My System”, “My Rack 1”, “My Server 1”, etc. are submitter-defined labels corresponding to their system topology.
# Rack-level systems are also supported:
# My System:
# - My Rack 1:
#   - Description: 'Optional Description'
#     Min PSUs Needed: 1
#     PSUs:
#     - Name: PSU 1
#       PowerCapacityWatts: 12000
#     - Name: PSU 2
#       PowerCapacityWatts: 12000
