#
# The yaml structure is composed of a system description, power info,
# and a list of nodes of various types.   All are required subsections.
#
system:                     include('system_description',required=True)
power:                      include('power_requirements',required=True)
nodes:
    client_nodes:           include('node_description',required=True)
    storage_data_nodes:     include('node_description',required=True)
    storage_metadata_nodes: include('node_description',required=False)

---
#
#
#
system_description:
    name:                   str(min=1)
    description:            str(min=1)
    storage_location:       enum('remote','local','hyper-converged')
    client_software:        enum('in-box','proprietary')
    storage_interface:      enum('block','file','object')
    required_rack_units:    int(min=1)
    shared_capabilities:
        multi_host_support:         enum('True','False')  # False is used for local storage
        simultaneous_write_support: enum('True','False')  # Are simultaneous writes by multiple hosts supported?
        simultaneous_read__support: enum('True','False')  # Are simultaneous reads by multiple hosts supported?
    max_sequential_read:    int(min=1,required=True)      # In GiB/s
    max_sequential_write:   int(min=1,required=True)      # In GiB/s
    max_random_read:        int(min=1,required=True)      # In GiB/s
    max_random_write:       int(min=1,required=True)      # In GiB/s

---
# Each on-prem MLPerf submission include the nameplate / design power of the submitted System Under Test (SUT).
# This information will complement existing measured-power methodologies and provide a uniform baseline reference across systems and vendors.
# The intent is not to replace measured power but to give additional visibility into the designed power capacity of submitted systems.
# By including design power, MLPerf can help stakeholders—submitters, reviewers, and end users—better contextualize energy efficiency results,
# improve reproducibility, and align with related MLCommons initiatives such as Storage and Training benchmarks that already collect rated
# power information.We propose to include the following:
# Option 1 (Preferred): Submit the aggregate nameplate / design power for the SUT, listing all major components (accelerators, CPUs, storage, networking, etc.).
# Option 2: Provide per-component TDP/TGP data and a summarized total for the SUT.
# === Reporting YAML FormatThe reported design power (total of all needed PSU capacities in watts) will appear alongside the measured-power and non-power views,
# clearly labeled as “Design Power.”This data is reported through a yaml file.
# The structure of the YAML file is a hierarchy of components, with the power capacity based on the DMTF RedFish PowerSupply schema.
# For example, a simple single-device system can have a single level:
# 
# My Device:
# - Description: 'Optional Description'
#   Min PSUs Needed: 1
#   PSUs:
#     - Name: PSU 1
#       PowerCapacityWatts: 1200
#     - Name: PSU 2
#       PowerCapacityWatts: 1200
#
# A more complex system can have two (or more) levels:
# My System:
# - My Rack 1:
#   - My Server 1:
#     - Description: 'Optional Description'
#       Min PSUs Needed: 1
#       PSUs:
#       - Name: PSU 1
#         PowerCapacityWatts: 1200
#       - Name: PSU 2
#         PowerCapacityWatts: 1200
#   - My Switch 1:
#     - Description: 'Optional Description'
#       Min PSUs needed: 1
#       PSUs:
#       - Name: PSU 1
#         PowerCapacityWatts: 1200
#       - Name: PSU 2
#         PowerCapacityWatts: 1200
# 
# The labels “My System”, “My Rack 1”, “My Server 1”, etc. are submitter-defined labels corresponding to their system topology.
# Rack-level systems are also supported:
# My System:
# - My Rack 1:
#   - Description: 'Optional Description'
#     Min PSUs Needed: 1
#     PSUs:
#     - Name: PSU 1
#       PowerCapacityWatts: 12000
#     - Name: PSU 2
#       PowerCapacityWatts: 12000
power_requirements:
    provisioned:            include('power_summary',required=True)
    consumed:               include('power_summary',required=False)
---
power_summary:
    storage_data_node:      include('power_detail')
    storage_metdata_node:   include('power_detail')
    backend_switch:         include('power_detail')
---
power_detail:
    quantity:               int(min=1)
    psu1_nameplate_power:   int(min=1,required=True)      # in watts
    psu2_nameplate_power:   int(min=1,required=False)     # in watts
    psu3_nameplate_power:   int(min=1,required=False)     # in watts
    psu4_nameplate_power:   int(min=1,required=False)     # in watts
    psu5_nameplate_power:   int(min=1,required=False)     # in watts
    psu6_nameplate_power:   int(min=1,required=False)     # in watts
    design_power:           int(min=1)                    # in Watts
    num_active_psus:        int(min=1)
    num_passive_psus:       int(min=0)

---
# 
# 
# 
node_description:
    quantity:               int(min=1)
    hardware:               include('hardware_description')
    networking:             list(include('network_instance'),min=1)
    operating_system:       include('operating_system_description')
    tuning:
        # All non-default tunings for OS need to be listed
        mpi_configuration:
            environment_variables: <list>
            version: Open MPI 4.1.4
        sysctl_parameters:
            <list all non-default parameters>

---
hardware_description:
    model:                  str(min=1)
    rack_units:             int(min=1)
    power_supplies:         int(min=1)
    psu_configuration:      enum('active/passive','active/active')
    psu_rating:             int(min=1)
    memory_capacity:        int(min=1)  # in GB, eg: 256
    memory_configuration:   8x32GB
    cpu_qty:                int(min=1)
    cpu_model:              str(min=1)
    cpu_cores:              int(min=1)
---
network_instance:
    type:                   enum('management','data','backend')
    model:                  str(min=1)
    speed:                  int(min=1)  # in Gb/s
    qty:                    int(min=1)
---
operating_system_description:
    name:                   str(min=1)
    version:                str(min=1)
    release_date:           str(min=1)
    kernel_version:         str(min=1)
    cpu_architecture:       enum('x86','arm')
